id:
  type: str
  mandatory: true
name:
  type: str
  mandatory: true
trigger:
  type: str
  mandatory: false
is_active:
  type: bool
  mandatory: false
created_by:
  type: str
  mandatory: true
created_at:
  type: datetime
  mandatory: false
modified_by:
  type: str
  mandatory: false
modified_at:
  type: datetime
  mandatory: false
flow_file:
  type: str
  mandatory: false
